import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'

const THOUGHTS_FILE = path.resolve('src/data/admin-thoughts.ts')
const CASE_STUDIES_FILE = path.resolve('src/data/admin-case-studies.ts')
const UPLOADS_DIR = path.resolve('public/uploads')

export default defineConfig({
  plugins: [
    react(),
    {
      name: 'admin-api',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          if (!req.url?.startsWith('/api/')) return next()

          res.setHeader('Content-Type', 'application/json')

          // GET /api/thoughts — return current admin articles as JSON
          if (req.url === '/api/thoughts' && req.method === 'GET') {
            try {
              const src = fs.readFileSync(THOUGHTS_FILE, 'utf-8')
              // Extract the array literal from the TS file
              const match = src.match(/export const adminThoughts[^=]*=\s*(\[[\s\S]*\]);/)
              res.end(match ? match[1] : '[]')
            } catch {
              res.end('[]')
            }
            return
          }

          // POST /api/thoughts — save admin articles (body is JSON array)
          if (req.url === '/api/thoughts' && req.method === 'POST') {
            let body = ''
            req.on('data', (chunk: Buffer) => { body += chunk.toString() })
            req.on('end', () => {
              try {
                const articles = JSON.parse(body)
                const formatted = JSON.stringify(articles, null, 2)
                const content =
                  `// AUTO-GENERATED by Admin Panel — edit at /admin, do not edit manually\n` +
                  `// eslint-disable-next-line @typescript-eslint/no-explicit-any\n` +
                  `export const adminThoughts: any[] = ${formatted};\n`
                fs.writeFileSync(THOUGHTS_FILE, content, 'utf-8')
                res.end('{"ok":true}')
              } catch {
                res.statusCode = 400
                res.end('{"error":"Invalid JSON"}')
              }
            })
            return
          }

          // GET /api/case-studies — return current admin case studies as JSON
          if (req.url === '/api/case-studies' && req.method === 'GET') {
            try {
              const src = fs.readFileSync(CASE_STUDIES_FILE, 'utf-8')
              const match = src.match(/export const adminCaseStudies[^=]*=\s*(\[[\s\S]*\]);/)
              res.end(match ? match[1] : '[]')
            } catch {
              res.end('[]')
            }
            return
          }

          // POST /api/case-studies — save admin case studies (body is JSON array)
          if (req.url === '/api/case-studies' && req.method === 'POST') {
            let body = ''
            req.on('data', (chunk: Buffer) => { body += chunk.toString() })
            req.on('end', () => {
              try {
                const studies = JSON.parse(body)
                const formatted = JSON.stringify(studies, null, 2)
                const content =
                  `// AUTO-GENERATED by Admin Panel — edit at /admin, do not edit manually\n` +
                  `// eslint-disable-next-line @typescript-eslint/no-explicit-any\n` +
                  `export const adminCaseStudies: any[] = ${formatted};\n`
                fs.writeFileSync(CASE_STUDIES_FILE, content, 'utf-8')
                res.end('{"ok":true}')
              } catch {
                res.statusCode = 400
                res.end('{"error":"Invalid JSON"}')
              }
            })
            return
          }

          // POST /api/upload — save image file, return public path
          if (req.url === '/api/upload' && req.method === 'POST') {
            let body = ''
            req.on('data', (chunk: Buffer) => { body += chunk.toString() })
            req.on('end', () => {
              try {
                const { name, data } = JSON.parse(body) as { name: string; data: string }
                const safe = path.basename(name).replace(/[^a-zA-Z0-9._-]/g, '_')
                const filename = `${Date.now()}_${safe}`
                const b64 = data.replace(/^data:[^;]+;base64,/, '')
                if (!fs.existsSync(UPLOADS_DIR)) {
                  fs.mkdirSync(UPLOADS_DIR, { recursive: true })
                }
                fs.writeFileSync(path.join(UPLOADS_DIR, filename), Buffer.from(b64, 'base64'))
                res.end(JSON.stringify({ path: `/uploads/${filename}` }))
              } catch {
                res.statusCode = 400
                res.end('{"error":"Upload failed"}')
              }
            })
            return
          }

          res.statusCode = 404
          res.end('{"error":"Not found"}')
        })
      },
    },
  ],
})
